#
# Module manifest for module 'InovativResources'
#
# Generated by: Stijn Callebaut
#
# Generated on: 1/25/2015
#
@{

# Script module or binary module file associated with this manifest.
 RootModule = 'iTimeZone.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '1be52967-2f07-4780-a5a9-05605e9f6eda'

# Author of this module
Author = 'Stijn Callebaut'

# Company or vendor of this module
CompanyName = 'Inovativ'

# Copyright statement for this module
Copyright = '(c) 2015 Stijn Callebaut. All rights reserved.'

# Description of the functionality provided by this module
 Description = 'Example Class DSC Resource to set the timezone'

# Minimum version of the Windows PowerShell engine required by this module
 PowerShellVersion = '5.0'
}
